-- Insert 50 dummy prompts into the prompts table
-- Replace 'your-user-id-here' with your actual user ID from the previous query

INSERT INTO prompts (id, user_id, title, content, category, tags, source_url, author, notes, usage_count, created_at, updated_at) VALUES

-- Writing & Content Creation (10 prompts)
(gen_random_uuid(), 'your-user-id-here', 'Blog Post Outline Generator', 'Create a detailed outline for a blog post about [TOPIC]. Include an engaging introduction, 3-5 main points with subpoints, and a compelling conclusion. Target audience: [AUDIENCE]', 'Writing', ARRAY['blog', 'outline', 'content'], 'https://twitter.com/promptexample1', 'ContentCreator', 'Great for structured blog writing', 5, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Email Subject Line Creator', 'Generate 10 compelling email subject lines for [EMAIL_TYPE] targeting [AUDIENCE]. Make them attention-grabbing but not spammy. Include emotional triggers and urgency where appropriate.', 'Writing', ARRAY['email', 'marketing', 'subject-lines'], 'https://reddit.com/r/prompts/example1', 'EmailExpert', 'Increases open rates significantly', 12, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Social Media Caption Writer', 'Write an engaging social media caption for [PLATFORM] about [TOPIC]. Include relevant hashtags, a call-to-action, and match the tone to the platform. Keep it under [CHARACTER_LIMIT] characters.', 'Writing', ARRAY['social-media', 'captions', 'marketing'], 'https://discord.com/channels/example1', 'SocialGuru', 'Works great for Instagram and LinkedIn', 8, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Product Description Generator', 'Create a compelling product description for [PRODUCT_NAME]. Highlight key features, benefits, and unique selling points. Target audience: [TARGET_AUDIENCE]. Tone: [TONE]. Include a strong call-to-action.', 'Writing', ARRAY['ecommerce', 'product', 'description'], 'https://example-marketplace.com/prompt1', 'EcommerceWriter', 'Boosts conversion rates', 15, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Press Release Template', 'Write a professional press release for [COMPANY] announcing [NEWS/EVENT]. Include headline, dateline, lead paragraph, body paragraphs with quotes, and boilerplate. Follow AP style guidelines.', 'Writing', ARRAY['pr', 'press-release', 'business'], 'https://twitter.com/prexpert/status/example', 'PRProfessional', 'Media-ready format', 3, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Creative Story Starter', 'Begin a creative story with this premise: [PREMISE]. Set it in [SETTING] during [TIME_PERIOD]. Main character: [CHARACTER_DESCRIPTION]. Write the opening 200 words with vivid descriptions and dialogue.', 'Writing', ARRAY['creative', 'story', 'fiction'], 'https://reddit.com/r/WritingPrompts/example', 'StoryTeller', 'Great for overcoming writer''s block', 7, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Technical Documentation Writer', 'Create clear technical documentation for [FEATURE/PROCESS]. Include overview, prerequisites, step-by-step instructions, code examples, troubleshooting section, and FAQ. Target audience: [SKILL_LEVEL] developers.', 'Writing', ARRAY['technical', 'documentation', 'development'], 'https://github.com/example/prompts', 'TechWriter', 'Saves hours of documentation time', 9, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Newsletter Content Creator', 'Create content for a weekly newsletter about [INDUSTRY/TOPIC]. Include: catchy subject line, personal intro, 3 main news items with commentary, featured resource, and engaging sign-off. Tone: [TONE].', 'Writing', ARRAY['newsletter', 'content', 'email'], 'https://substack.com/example-prompt', 'NewsletterPro', 'Consistent engagement booster', 11, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Grant Proposal Writer', 'Write a compelling grant proposal for [PROJECT/ORGANIZATION]. Include executive summary, problem statement, proposed solution, budget overview, and expected outcomes. Target funder: [FUNDER_TYPE].', 'Writing', ARRAY['grant', 'proposal', 'nonprofit'], 'https://example-nonprofit.org/resources', 'GrantWriter', 'Helped secure $50K+ in funding', 4, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Video Script Creator', 'Create a script for a [DURATION]-minute video about [TOPIC]. Include hook, main content points, transitions, call-to-action, and visual cues. Target audience: [AUDIENCE]. Platform: [PLATFORM].', 'Writing', ARRAY['video', 'script', 'content'], 'https://youtube.com/example-creator', 'VideoCreator', 'Perfect for YouTube and TikTok', 13, NOW(), NOW()),

-- Business & Marketing (10 prompts)
(gen_random_uuid(), 'your-user-id-here', 'SWOT Analysis Generator', 'Conduct a comprehensive SWOT analysis for [COMPANY/PROJECT]. Identify 5 strengths, 5 weaknesses, 5 opportunities, and 5 threats. Provide actionable insights and strategic recommendations based on the analysis.', 'Business', ARRAY['swot', 'analysis', 'strategy'], 'https://linkedin.com/posts/business-analyst', 'StrategyConsultant', 'Essential for strategic planning', 6, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Customer Persona Creator', 'Create a detailed customer persona for [PRODUCT/SERVICE]. Include demographics, psychographics, pain points, goals, preferred communication channels, and buying behavior. Name the persona and give them a backstory.', 'Business', ARRAY['persona', 'marketing', 'customer'], 'https://marketingland.com/example-article', 'MarketingManager', 'Improved targeting by 40%', 14, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Competitive Analysis Framework', 'Analyze [NUMBER] competitors for [YOUR_COMPANY] in the [INDUSTRY] space. Compare pricing, features, marketing strategies, strengths, and weaknesses. Identify market gaps and opportunities.', 'Business', ARRAY['competitive', 'analysis', 'research'], 'https://twitter.com/bizanalyst/thread', 'BusinessAnalyst', 'Reveals market opportunities', 8, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Sales Pitch Generator', 'Create a compelling sales pitch for [PRODUCT/SERVICE] targeting [TARGET_AUDIENCE]. Include problem identification, solution presentation, benefits, social proof, and strong closing. Duration: [TIME_LIMIT].', 'Business', ARRAY['sales', 'pitch', 'presentation'], 'https://salesforce.com/resources/example', 'SalesDirector', 'Increased close rate by 25%', 19, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Business Model Canvas', 'Create a business model canvas for [BUSINESS_IDEA]. Define value propositions, customer segments, channels, customer relationships, revenue streams, key resources, key activities, key partnerships, and cost structure.', 'Business', ARRAY['business-model', 'canvas', 'startup'], 'https://strategyzer.com/example', 'StartupAdvisor', 'Perfect for startup planning', 7, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Market Research Survey', 'Design a market research survey for [PRODUCT/SERVICE] with [NUMBER] questions. Include demographic questions, usage patterns, pain points, feature preferences, and pricing sensitivity. Ensure unbiased question structure.', 'Business', ARRAY['market-research', 'survey', 'data'], 'https://surveymonkey.com/examples', 'MarketResearcher', 'Gathered insights from 500+ responses', 5, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'ROI Calculator Prompt', 'Calculate the ROI for [INVESTMENT/PROJECT] over [TIME_PERIOD]. Include initial investment, ongoing costs, revenue projections, risk factors, and break-even analysis. Present in clear, executive-friendly format.', 'Business', ARRAY['roi', 'finance', 'analysis'], 'https://example-consulting.com/tools', 'FinanceConsultant', 'Justified $100K+ investments', 9, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Crisis Communication Plan', 'Develop a crisis communication plan for [SCENARIO] affecting [COMPANY]. Include immediate response steps, key messages, stakeholder communication strategy, media response, and recovery actions.', 'Business', ARRAY['crisis', 'communication', 'pr'], 'https://prsa.org/example-resource', 'CrisisManager', 'Prevented major reputation damage', 2, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Employee Onboarding Checklist', 'Create a comprehensive onboarding checklist for new [ROLE] employees at [COMPANY]. Include pre-arrival tasks, first day activities, first week goals, training schedule, and 90-day milestones.', 'Business', ARRAY['onboarding', 'hr', 'checklist'], 'https://hr-blog.com/onboarding-best-practices', 'HRDirector', 'Reduced time-to-productivity by 30%', 12, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Partnership Proposal Template', 'Draft a partnership proposal between [YOUR_COMPANY] and [PARTNER_COMPANY]. Include partnership objectives, mutual benefits, proposed collaboration structure, success metrics, and next steps.', 'Business', ARRAY['partnership', 'proposal', 'collaboration'], 'https://business-partnerships.com/templates', 'BizDev', 'Secured 3 major partnerships', 6, NOW(), NOW()),

-- Programming & Development (10 prompts)
(gen_random_uuid(), 'your-user-id-here', 'Code Review Checklist', 'Create a comprehensive code review checklist for [PROGRAMMING_LANGUAGE] projects. Include code quality, security, performance, maintainability, and documentation criteria. Add specific items for [FRAMEWORK] if applicable.', 'Programming', ARRAY['code-review', 'quality', 'checklist'], 'https://github.com/google/eng-practices', 'SeniorDev', 'Improved code quality across team', 16, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'API Documentation Generator', 'Generate comprehensive API documentation for [API_NAME]. Include endpoint descriptions, request/response examples, authentication, error codes, rate limiting, and SDK examples in [LANGUAGE].', 'Programming', ARRAY['api', 'documentation', 'development'], 'https://swagger.io/resources/example', 'APIArchitect', 'Reduced support tickets by 60%', 11, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Database Schema Designer', 'Design a database schema for [APPLICATION_TYPE]. Include entity relationships, primary/foreign keys, indexes, constraints, and sample data. Consider scalability and normalization best practices.', 'Programming', ARRAY['database', 'schema', 'design'], 'https://stackoverflow.com/questions/example', 'DatabaseArchitect', 'Handles 1M+ records efficiently', 8, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Unit Test Generator', 'Generate unit tests for [FUNCTION/CLASS] in [PROGRAMMING_LANGUAGE]. Include positive cases, negative cases, edge cases, and mock dependencies. Use [TESTING_FRAMEWORK] syntax and best practices.', 'Programming', ARRAY['testing', 'unit-tests', 'quality'], 'https://testing-library.com/docs/example', 'QAEngineer', 'Achieved 95% test coverage', 13, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Performance Optimization Guide', 'Analyze and optimize [APPLICATION/FEATURE] for better performance. Identify bottlenecks, suggest improvements for [SPECIFIC_AREAS], and provide before/after metrics. Include monitoring recommendations.', 'Programming', ARRAY['performance', 'optimization', 'monitoring'], 'https://web.dev/performance-example', 'PerformanceEngineer', 'Reduced load time by 70%', 7, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Security Audit Checklist', 'Create a security audit checklist for [APPLICATION_TYPE] built with [TECHNOLOGY_STACK]. Include authentication, authorization, data validation, encryption, and common vulnerability checks.', 'Programming', ARRAY['security', 'audit', 'vulnerability'], 'https://owasp.org/example-guide', 'SecurityEngineer', 'Prevented 3 major security issues', 9, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'CI/CD Pipeline Template', 'Design a CI/CD pipeline for [PROJECT_TYPE] using [CI_TOOL]. Include build stages, testing phases, deployment strategies, rollback procedures, and monitoring integration.', 'Programming', ARRAY['cicd', 'devops', 'automation'], 'https://github.com/actions/example-workflow', 'DevOpsEngineer', 'Reduced deployment time by 80%', 14, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Code Architecture Review', 'Review the architecture of [PROJECT_NAME] and suggest improvements. Analyze design patterns, separation of concerns, scalability, maintainability, and adherence to [ARCHITECTURE_PATTERN] principles.', 'Programming', ARRAY['architecture', 'design', 'review'], 'https://martinfowler.com/architecture/example', 'SoftwareArchitect', 'Improved system maintainability', 5, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Error Handling Strategy', 'Design a comprehensive error handling strategy for [APPLICATION_TYPE]. Include error classification, logging standards, user-friendly messages, recovery mechanisms, and monitoring alerts.', 'Programming', ARRAY['error-handling', 'logging', 'monitoring'], 'https://docs.example.com/error-handling', 'SeniorDeveloper', 'Reduced production errors by 50%', 10, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Microservices Migration Plan', 'Create a migration plan to break down [MONOLITHIC_APP] into microservices. Identify service boundaries, data migration strategy, communication patterns, and phased rollout approach.', 'Programming', ARRAY['microservices', 'migration', 'architecture'], 'https://microservices.io/patterns/example', 'CloudArchitect', 'Successfully migrated 5 services', 4, NOW(), NOW()),

-- Education & Learning (5 prompts)
(gen_random_uuid(), 'your-user-id-here', 'Lesson Plan Creator', 'Create a detailed lesson plan for teaching [SUBJECT] to [GRADE_LEVEL/AUDIENCE]. Include learning objectives, materials needed, activities, assessment methods, and homework assignments. Duration: [TIME].', 'Education', ARRAY['lesson-plan', 'teaching', 'curriculum'], 'https://education.com/lesson-plans/example', 'Teacher', 'Engaging for all learning styles', 18, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Study Guide Generator', 'Generate a comprehensive study guide for [EXAM/SUBJECT]. Include key concepts, important formulas, practice questions, mnemonics, and study schedule. Format for easy review and memorization.', 'Education', ARRAY['study-guide', 'exam-prep', 'learning'], 'https://quizlet.com/example-set', 'Student', 'Improved test scores by 20%', 15, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Interactive Quiz Creator', 'Create an interactive quiz about [TOPIC] with [NUMBER] questions. Include multiple choice, true/false, and short answer questions. Provide explanations for correct answers and difficulty progression.', 'Education', ARRAY['quiz', 'assessment', 'interactive'], 'https://kahoot.com/example-quiz', 'Educator', 'High student engagement rates', 12, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Learning Path Designer', 'Design a learning path for mastering [SKILL/SUBJECT]. Break down into modules, estimate time requirements, suggest resources, include practical projects, and define milestones.', 'Education', ARRAY['learning-path', 'curriculum', 'skill-development'], 'https://coursera.org/example-course', 'InstructionalDesigner', 'Completed by 200+ learners', 8, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Educational Game Concept', 'Design an educational game to teach [CONCEPT] to [AGE_GROUP]. Include game mechanics, learning objectives, progression system, rewards, and assessment integration. Make it fun and engaging!', 'Education', ARRAY['gamification', 'educational-games', 'engagement'], 'https://education-games.com/example', 'GameDesigner', 'Increased retention by 40%', 6, NOW(), NOW()),

-- Creative & Design (5 prompts)
(gen_random_uuid(), 'your-user-id-here', 'Brand Identity Generator', 'Create a complete brand identity for [COMPANY/PROJECT]. Include brand personality, color palette, typography suggestions, logo concepts, voice and tone guidelines, and brand application examples.', 'Creative', ARRAY['branding', 'identity', 'design'], 'https://behance.net/example-project', 'BrandDesigner', 'Client loved the cohesive identity', 9, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Creative Campaign Concept', 'Develop a creative campaign concept for [PRODUCT/CAUSE]. Include big idea, target audience, key messages, creative executions across channels, timeline, and success metrics.', 'Creative', ARRAY['campaign', 'advertising', 'creative'], 'https://adsoftheworld.com/example', 'CreativeDirector', 'Won industry recognition', 7, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'UI/UX Design Brief', 'Create a design brief for [APP/WEBSITE] targeting [USER_TYPE]. Include user personas, user journey, key features, design requirements, accessibility considerations, and success metrics.', 'Creative', ARRAY['ui', 'ux', 'design-brief'], 'https://dribbble.com/shots/example', 'UXDesigner', 'Improved user satisfaction by 35%', 11, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Photography Shot List', 'Create a detailed shot list for [EVENT/PROJECT] photography. Include must-have shots, creative angles, lighting considerations, equipment needed, and timeline. Style: [PHOTOGRAPHY_STYLE].', 'Creative', ARRAY['photography', 'shot-list', 'planning'], 'https://petapixel.com/example-article', 'Photographer', 'Captured all key moments perfectly', 5, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Content Calendar Template', 'Design a content calendar for [PLATFORM/BRAND] covering [TIME_PERIOD]. Include content themes, posting schedule, content types, hashtag strategy, and engagement tactics. Align with [GOALS].', 'Creative', ARRAY['content-calendar', 'social-media', 'planning'], 'https://hootsuite.com/resources/example', 'ContentManager', 'Increased engagement by 60%', 16, NOW(), NOW()),

-- Data & Analytics (5 prompts)
(gen_random_uuid(), 'your-user-id-here', 'Data Analysis Report', 'Analyze [DATASET] and create a comprehensive report. Include data cleaning steps, key findings, visualizations, statistical insights, trends, and actionable recommendations for [STAKEHOLDER].', 'Data', ARRAY['data-analysis', 'reporting', 'insights'], 'https://kaggle.com/example-notebook', 'DataAnalyst', 'Identified $50K cost savings', 10, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'KPI Dashboard Design', 'Design a KPI dashboard for [DEPARTMENT/FUNCTION]. Define key metrics, data sources, visualization types, update frequency, and alert thresholds. Include both operational and strategic KPIs.', 'Data', ARRAY['kpi', 'dashboard', 'metrics'], 'https://tableau.com/example-dashboard', 'DataVisualization', 'Improved decision-making speed', 8, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'A/B Test Design', 'Design an A/B test for [FEATURE/CHANGE]. Define hypothesis, success metrics, sample size calculation, test duration, statistical significance requirements, and analysis plan.', 'Data', ARRAY['ab-testing', 'experimentation', 'statistics'], 'https://optimizely.com/example-test', 'GrowthAnalyst', 'Achieved 15% conversion lift', 12, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Predictive Model Proposal', 'Propose a predictive model for [BUSINESS_PROBLEM]. Include problem definition, data requirements, model approach, evaluation metrics, implementation plan, and expected business impact.', 'Data', ARRAY['machine-learning', 'predictive', 'modeling'], 'https://towards-data-science.com/example', 'DataScientist', 'Improved forecast accuracy by 25%', 6, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Data Governance Framework', 'Establish a data governance framework for [ORGANIZATION]. Include data quality standards, access controls, privacy policies, retention policies, and compliance requirements for [REGULATIONS].', 'Data', ARRAY['data-governance', 'compliance', 'quality'], 'https://data-governance.com/framework', 'DataGovernance', 'Ensured regulatory compliance', 4, NOW(), NOW()),

-- Personal & Productivity (5 prompts)
(gen_random_uuid(), 'your-user-id-here', 'Goal Setting Framework', 'Create a comprehensive goal-setting plan for [TIME_PERIOD]. Use SMART criteria, break down into milestones, identify potential obstacles, create accountability measures, and define success metrics.', 'Personal', ARRAY['goals', 'planning', 'productivity'], 'https://mindtools.com/goal-setting', 'ProductivityCoach', 'Achieved 90% of set goals', 14, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Time Management Audit', 'Conduct a time management audit for [ROLE/PERSON]. Analyze current time allocation, identify time wasters, suggest optimization strategies, and create a more efficient daily schedule.', 'Personal', ARRAY['time-management', 'productivity', 'efficiency'], 'https://toggl.com/time-tracking-tips', 'TimeManagement', 'Saved 2 hours daily', 11, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Habit Formation Plan', 'Design a habit formation plan for [DESIRED_HABIT]. Include habit stacking, environmental design, tracking methods, reward systems, and strategies to overcome common obstacles.', 'Personal', ARRAY['habits', 'behavior-change', 'self-improvement'], 'https://jamesclear.com/atomic-habits', 'HabitCoach', 'Successfully formed 5 new habits', 13, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Decision Making Framework', 'Create a decision-making framework for [DECISION_TYPE]. Include criteria evaluation, pros/cons analysis, stakeholder impact assessment, risk evaluation, and implementation planning.', 'Personal', ARRAY['decision-making', 'framework', 'analysis'], 'https://decision-making-tools.com/example', 'DecisionAnalyst', 'Improved decision quality', 7, NOW(), NOW()),

(gen_random_uuid(), 'your-user-id-here', 'Learning Plan Template', 'Create a personalized learning plan for [SKILL/SUBJECT]. Include learning objectives, resource recommendations, practice exercises, progress tracking, and application opportunities.', 'Personal', ARRAY['learning', 'skill-development', 'growth'], 'https://coursera.org/learn/learning-how-to-learn', 'LearningCoach', 'Accelerated skill acquisition', 9, NOW(), NOW());
